# Generated by Django 2.2 on 2019-09-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_auto_20190912_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
