# Generated by Django 2.2 on 2019-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0004_post_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='timestap',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='published_data',
            field=models.DateTimeField(),
        ),
    ]
