# Generated by Django 2.2 on 2019-09-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0006_auto_20190913_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_model',
            options={'ordering': ['-published_data', '-updated_data']},
        ),
    ]
