# Generated by Django 2.2 on 2019-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0007_auto_20190913_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='published_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
