# Generated by Django 2.2 on 2019-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0008_auto_20190913_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
