# Generated by Django 2.2 on 2019-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0009_post_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
